spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization.write_dates_as_timestamps: false
    time-zone: GMT+8
  h2:
    console:
      enabled: true # 默认启动程序启动
      path: /h2 #访问路径 localhost:9100/h2
  datasource:
    platform: h2
    schema: classpath*:schema_h2.sql
    url: jdbc:h2:mem:user;MODE=mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password:
    driverClassName: org.h2.Driver
server:
  port: 8083
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.owl.common.entity
  typeEnumsPackage: com.owl.common.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    dbType: mysql
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
#    keyGenerator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false